# General
KMER: 8
SPECIE: "hCoV-19"

# INPUT DATA
PATH_FASTA_GISAID: "C:/Users/puddi/Desktop/CouGaR-g-master/gisaid_hcov-19_unico.fasta"
PATH_METADATA: "C:/Users/puddi/Desktop/CouGaR-g-master/gisaid_hcov-19_unico.tsv"
PATH_REFERENCE_GENOME: "C:/Users/puddi/Desktop/CouGaR-g-master/EPI_ISL_402124-ORF1ab.fasta"
CLADES: ['L','G','GR','GH','GV','GK','GRY','O','GRA']
LINEAGE: ['AY.120', 'AY.4', 'B.1', 'B.1.1', 'B.1.1.214', 'B.1.1.519', 'B.1.1.7', 'B.1.160', 'B.1.177', 'B.1.177.21', 'B.1.2', 'B.1.221', 'B.1.243', 'B.1.258', 'B.1.351', 'B.1.427', 'B.1.427', 'B.1.526', 'B.1.617.2', 'D.2', 'P.1', 'R.1', 'B.1.617.1', 'B.1.525', 'C.37', 'B.1.621', 'BA.1', 'BA.2', 'BA.3', 'BA.4', 'BA.5', 'BA.2.12.1', 'BA.2.75', 'BQ.1', 'XBB', 'B.1.1.529' ]
SAMPLES_PER_CLADE: 20000

# MODEL
TRAIN_SIZE: 0.8 # size for val and test sets: (1-TRAIN_SIZE)/2
BATCH_SIZE: 16
EPOCHS: 50
PREPROCESSING: {"divide_by_max": {}} # ("name_function", dict_kwargs)
WEIGHTS_PATH: null

# REPRODUCIBILITY
SEED: 42